title: Command line navigation
hero_image: images/banner.png
description: Key commands of the command line
version: 4
listed: false
copyedit: false
last_tested: "2018-05-09"
steps:
  - title: Command line navigation
